### ISSUE TITLE
Use new @resultBuilder instead of @_functionBuilder

### ISSUE THREAD

**Issue by gongzhang** [andtie/SequenceBuilder#1]
First of all, thank you for providing this package. The implementation is really amazing! Using `SequenceBuilder` is very helpful to implement custom container Views.

The new version of Swift provides a more complete `@resultBuilder`, which can replace the previous internal `@_functionBuilder`. This allows `SequenceBuilder` to support new syntax such as `if #available(...)` and other new syntax. 😄

**Comment by andtie** [comment]
Hi @gongzhang. Thanks for the reminder and the nice words!
