### ISSUE TITLE
Support for watchOS and tvOS

### ISSUE THREAD

**Issue by chenhaiteng** [andtie/SequenceBuilder#2]
Hi Andtie,
I like how you implement SequenceBuilder. It is really useful and elegant.
But when I try to apply it on watchOS, it shows "'View' is only available in watchOS 6.0 or newer" at Either+SwiftUI.swift.
Also, same error occurs on the `some` and `Identifiable`...
I think it would be good to update Package.swift as following:
```swift 
    platforms: [.macOS(.v11), .iOS(.v14), .watchOS(.v6), .tvOS(.v13)],
```
Thanks in advance.

**Comment by andtie** [comment]
Hi @chenhaiteng! Thanks for the heads up. I've updated the platforms-list.
